// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {live} from '../models';

export function Configuration():Promise<main.Config>;

export function LatestStandings():Promise<live.PredictedStandings>;

export function Login(arg1:string,arg2:string):Promise<boolean>;
