// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LatestStandings() {
  return window['go']['main']['App']['LatestStandings']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function ShowTopN() {
  return window['go']['main']['App']['ShowTopN']();
}
