// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {live} from '../models';

export function LatestStandings():Promise<live.PredictedStandings>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function PastResults():Promise<boolean>;
