name: Makefile CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'


    - name: Install dependencies
      run: make install

    - name: Run lint
      run: make lint

    - name: Run tests
      run: make test

    - name: Run cover check
      run: make cover-check
